import { jsPDF } from 'jspdf';

interface PDFGeneratorOptions {
  content: string;
  type: string;
  title?: string;
}

export function generatePDF({ content, type, title }: PDFGeneratorOptions) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;
  let yPosition = margin;

  // Add logo and header
  addHeader(doc, pageWidth, yPosition);
  yPosition += 25;

  // Add title (left aligned)
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(37, 99, 235); // Blue color
  const titleText = title || `${capitalizeFirstLetter(type)} Notes`;
  doc.text(titleText, margin, yPosition);
  yPosition += 15;

  // Add separator line
  doc.setDrawColor(229, 231, 235);
  doc.setLineWidth(0.5);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 10;

  // Process and add content
  doc.setTextColor(0, 0, 0);
  yPosition = addContent(doc, content, margin, yPosition, contentWidth, pageHeight, type);

  // Add footer to all pages
  addFooter(doc);

  // Save the PDF
  const fileName = `${type.replace(/\s+/g, '-')}-${Date.now()}.pdf`;
  doc.save(fileName);
}

function addHeader(doc: jsPDF, pageWidth: number, yPosition: number) {
  // Add logo - stylized "S" shape with blue gradient effect
  doc.setFillColor(37, 99, 235); // Blue
  doc.roundedRect(20, yPosition, 15, 15, 2, 2, 'F');
  
  // Add stylized "S" text in logo
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text('S', 27.5, yPosition + 10.5, { align: 'center' });

  // Add app name "Studia"
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(37, 99, 235);
  doc.text('Studia', 38, yPosition + 11);

  // Add tagline
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(107, 114, 128);
  doc.text('AI-Powered Learning', 38, yPosition + 16);

  // Add date in top right corner
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(107, 114, 128);
  const dateText = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'short', 
    day: 'numeric' 
  });
  doc.text(dateText, pageWidth - 20, yPosition + 11, { align: 'right' });
}

function addFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    
    // Footer line
    doc.setDrawColor(229, 231, 235);
    doc.setLineWidth(0.3);
    doc.line(20, pageHeight - 15, pageWidth - 20, pageHeight - 15);
    
    // Footer text
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(107, 114, 128);
    doc.text('Generated by Studia', 20, pageHeight - 10);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 20, pageHeight - 10, { align: 'right' });
  }
}

function addContent(
  doc: jsPDF,
  content: string,
  margin: number,
  startY: number,
  contentWidth: number,
  pageHeight: number,
  type: string
): number {
  let yPosition = startY;
  const lineHeight = 6;
  const maxY = pageHeight - 25; // Leave space for footer

  // Parse markdown-like content
  const lines = content.split('\n');
  
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    
    if (!line) {
      yPosition += lineHeight / 2;
      continue;
    }

    // Check if we need a new page
    if (yPosition > maxY) {
      doc.addPage();
      yPosition = margin;
    }

    // Handle headings
    if (line.startsWith('# ')) {
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(37, 99, 235);
      const text = line.substring(2);
      yPosition = addWrappedText(doc, text, margin, yPosition, contentWidth, lineHeight * 1.2, maxY);
      yPosition += lineHeight;
    } else if (line.startsWith('## ')) {
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(37, 99, 235);
      const text = line.substring(3);
      yPosition = addWrappedText(doc, text, margin, yPosition, contentWidth, lineHeight * 1.1, maxY);
      yPosition += lineHeight * 0.8;
    } else if (line.startsWith('### ')) {
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(55, 65, 81);
      const text = line.substring(4);
      yPosition = addWrappedText(doc, text, margin, yPosition, contentWidth, lineHeight, maxY);
      yPosition += lineHeight * 0.6;
    } else if (line.startsWith('- ') || line.startsWith('* ')) {
      // Bullet points
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(55, 65, 81);
      const text = line.substring(2);
      doc.text('•', margin + 2, yPosition);
      yPosition = addWrappedText(doc, text, margin + 7, yPosition, contentWidth - 7, lineHeight, maxY);
      yPosition += lineHeight * 0.3;
    } else if (/^\d+\.\s/.test(line)) {
      // Numbered lists
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(55, 65, 81);
      const match = line.match(/^(\d+\.)\s(.+)/);
      if (match) {
        doc.text(match[1], margin + 2, yPosition);
        yPosition = addWrappedText(doc, match[2], margin + 10, yPosition, contentWidth - 10, lineHeight, maxY);
        yPosition += lineHeight * 0.3;
      }
    } else if (line.startsWith('**') && line.endsWith('**')) {
      // Bold text
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(17, 24, 39);
      const text = line.substring(2, line.length - 2);
      yPosition = addWrappedText(doc, text, margin, yPosition, contentWidth, lineHeight, maxY);
      yPosition += lineHeight * 0.5;
    } else {
      // Regular text
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(55, 65, 81);
      yPosition = addWrappedText(doc, line, margin, yPosition, contentWidth, lineHeight, maxY);
      yPosition += lineHeight * 0.3;
    }
  }

  return yPosition;
}

function addWrappedText(
  doc: jsPDF,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight: number,
  maxY: number
): number {
  const lines = doc.splitTextToSize(text, maxWidth);
  let currentY = y;

  for (const line of lines) {
    if (currentY > maxY) {
      doc.addPage();
      currentY = 20;
    }
    doc.text(line, x, currentY);
    currentY += lineHeight;
  }

  return currentY;
}

function capitalizeFirstLetter(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
